### ISSUE TITLE
Autoscaler fails during scale call

### ISSUE THREAD

**Issue by alenkacz** [alenkacz/marathon-rabbitmq-autoscale#33]
Exception in thread "main" MarathonException{}
	at mesosphere.marathon.client.MarathonClient$MarathonErrorDecoder.decode(MarathonClient.java:30)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy5.updateApp(Unknown Source)
	at cz.alenkacz.marathon.scaler.MarathonProxy$.scale(MarathonProxy.scala:56)
	at cz.alenkacz.marathon.scaler.MarathonProxy$.scaleUp(MarathonProxy.scala:18)
	at cz.alenkacz.marathon.scaler.Main$.$anonfun$checkAndScale$1(Main.scala:67)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at cz.alenkacz.marathon.scaler.Main$.checkAndScale(Main.scala:58)
	at cz.alenkacz.marathon.scaler.Main$.main(Main.scala:162)
	at cz.alenkacz.marathon.scaler.Main.main(Main.scala)

**Comment by alenkacz** [comment]
fixed by #34
