### ISSUE TITLE
Multiple RMQ Monitor Throwing Error

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [alenkacz/marathon-rabbitmq-autoscale#37]
I have two rabbit MQ Servers to be monitored. I am giving the Names as RMQ1 and RMQ2.
There are applications available with labels, 
AUTOSCALE_RMQSERVER=RMQ1
AUTOSCALE_RMQSERVER=RMQ2

When i start the autoscaler with the below configuration - its throwing error saying -
```
Exception in thread "main" cz.alenkacz.marathon.scaler.InvalidConfigurationException: RabbitMq configuration cannot contain multiple rabbitMq servers without a name specified
	at cz.alenkacz.marathon.scaler.Main$.setupRabbitMqClients(Main.scala:119)
	at cz.alenkacz.marathon.scaler.Main$.main(Main.scala:134)
	at cz.alenkacz.marathon.scaler.Main.main(Main.scala)
```

When i remove one RMQ server and start it, it is working properly. But i need to monitor both the RMQs.
My Marathon.json configuration is -

```
{
  "id": "/rabbitmq-autoscaler",
  "cpus": 1,
  "mem": 1024,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "forcePullImage": true,
      "image": "custom-registry/rabbitmq-autoscaler",
      "privileged": false
    },
    "portMappings": [
      {
        "containerPort": 0,
        "hostPort": 0,
        "name": "default",
        "protocol": "tcp",
        "servicePort": 10001
      }
    ]
  },
  "env": {
    "JAVA_OPTS": "-DrabbitMq.0.username=user1 -DrabbitMq.0.password=pass1 -DrabbitMq.0.httpApiEndpoint=http://server1.com:15672/api -DrabbitMq.0.name=RMQ1 -DrabbitMq.1.username=user2 -DrabbitMq.1.password=pass2 -DrabbitMq.1.httpApiEndpoint=http://server2.com:15672/api -DrabbitMq.1.name=RMQ2 -Dmarathon.url=http://marathonurl.com:8080"
  },
  "networks": [
    {
      "mode": "container/bridge"
    }
  ]
}
```

**Comment by augi** [comment]
As I'm looking [at the code](https://github.com/alenkacz/marathon-rabbitmq-autoscale/blob/master/src/main/scala/cz/alenkacz/marathon/scaler/Main.scala#L109), it seems that it requires that one of the servers must be without name.

IMHO the check should be changed to this:
```scala
private def rabbitMqConfigValid(rabbitMqConfigs: Seq[Config]) =
   rabbitMqConfigs.count(c => c.getOptionalString("name").isDefined) >= (rabbitMqConfigs.size - 1) // max one config can be without name 
```

**Comment by AbacusIntegrationPlatform** [comment]
Thank you.
For now, I have changed the config to below and it started working.
```
{
  "id": "/rabbitmq-autoscaler",
  "cpus": 1,
  "mem": 1024,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "forcePullImage": true,
      "image": "custom-registry/rabbitmq-autoscaler",
      "privileged": false
    },
    "portMappings": [
      {
        "containerPort": 0,
        "hostPort": 0,
        "name": "default",
        "protocol": "tcp",
        "servicePort": 10001
      }
    ]
  },
  "env": {
    "JAVA_OPTS": "-DrabbitMq.0.username=user1 -DrabbitMq.0.password=pass1 -DrabbitMq.0.httpApiEndpoint=http://server1.com:15672/api -DrabbitMq.0.name=RMQ1 -DrabbitMq.1.username=user2 -DrabbitMq.1.password=pass2 -DrabbitMq.1.httpApiEndpoint=http://server2.com:15672/api -DrabbitMq.1.name=RMQ2 DrabbitMq.2.username=user3 -DrabbitMq.2.password=pass3 -DrabbitMq.2.httpApiEndpoint=http://dummyserver2.com:15672/api -Dmarathon.url=http://marathonurl.com:8080"
  },
  "networks": [
    {
      "mode": "container/bridge"
    }
  ]
}
```

I have added a dummy entry without any name.
