### ISSUE TITLE
Autoscaler failing to start when basic Authentication is enabled in Marathon

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [alenkacz/marathon-rabbitmq-autoscale#38]
The autoscaler is failing to start with the below error while basic authentication is enabled in Marathon API. Clearly says, it is expecting to authentication details to be passed to validate. Do we have a provision to send the user/pass to marathon in the autoscaler ?

```
Exception in thread "main" Unauthorized (http status: 401)
	at mesosphere.marathon.client.MarathonClient$MarathonErrorDecoder.decode(MarathonClient.java:30)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:126)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy3.getApps(Unknown Source)
	at cz.alenkacz.marathon.scaler.MarathonProxy$.findAppsWithAutoscaleLabels(MarathonProxy.scala:72)
	at cz.alenkacz.marathon.scaler.Main$.main(Main.scala:151)
	at cz.alenkacz.marathon.scaler.Main.main(Main.scala)
```

**Comment by AbacusIntegrationPlatform** [comment]
Solution is to update the marathon Client connection - to below in Main.scala.

```
val marathonClient =
      MarathonClient.getInstanceWithBasicAuth(marathonConfig.getString("url"), marathonConfig.getString("username"), marathonConfig.getString("password"))
```

Also update the reference.conf to have the basic auth details (Username/pass)
